name: microspotreader
channels:
  - defaults
dependencies:
  - pip
  - plotly=5.9.0
  - python=3.11.5
  - setuptools=68.0.0
  - libglib
  - pip:
    - streamlit
    - matplotlib==3.8.0
    - scipy==1.11.3
    - pandas==2.1.2
    - pyopenms==3.1.0
    - numba==0.59.0
    - seaborn==0.13.2
    - scikit-image
    - imagecodecs==2023.9.18
