name: microspotreader
channels:
  - defaults
dependencies:
  # - bzip2=1.0.8
  # - ca-certificates=2023.08.22
  # - libffi=3.4.4
  # - openssl=3.0.12
  - pip
  - plotly=5.9.0
  - python=3.11.5
  - setuptools=68.0.0
  - libglib
  # - sqlite=3.41.2
  # - tk=8.6.12
  # - vc=14.2
  # - wheel=0.41.2
  # - xz=5.4.2
  # - zlib=1.2.13
  - pip:
    - streamlit
    - matplotlib==3.8.0
    - scipy==1.11.3
    - pandas==2.1.2
    - pyopenms==3.1.0
    - numba==0.59.0
    - seaborn==0.13.2
    - scikit-image
  #     - altair==5.1.2
  #     - ansi2html==1.8.0
  #     - asttokens==2.4.1
  #     - attrs==23.1.0
  #     - backcall==0.2.0
  #     - blinker==1.6.3
  #     - cachetools==5.3.2
  #     - certifi==2023.7.22
  #     - charset-normalizer==3.3.1
  #     - click==8.1.7
  #     - colorama==0.4.6
  #     - comm==0.1.4
  #     - contourpy==1.1.1
  #     - cycler==0.12.1
  #     - dash==2.14.1
  #     - dash-core-components==2.0.0
  #     - dash-html-components==2.0.0
  #     - dash-table==5.0.0
  #     - debugpy==1.8.0
  #     - decorator==5.1.1
  #     - executing==2.0.0
  #     - flask==3.0.0
  #     - fonttools==4.43.1
  #     - gitdb==4.0.11
  #     - gitpython==3.1.40
  #     - idna==3.4
  #     - imagecodecs==2023.9.18
  #     - imageio==2.31.6
  #     - importlib-metadata==6.8.0
  #     - ipykernel==6.27.0
  #     - ipympl==0.9.3
  #     - ipython==8.16.1
  #     - ipython-genutils==0.2.0
  #     - ipywidgets==8.1.1
  #     - itsdangerous==2.1.2
  #     - jedi==0.19.1
  #     - jinja2==3.1.2
  #     - jsonschema==4.19.1
  #     - jsonschema-specifications==2023.7.1
  #     - jupyter-client==8.6.0
  #     - jupyter-core==5.5.0
  #     - jupyter-dash==0.4.2
  #     - jupyterlab-widgets==3.0.9
  #     - kiwisolver==1.4.5
  #     - lazy-loader==0.3
  #     - llvmlite==0.42.0
  #     - markdown-it-py==3.0.0
  #     - markupsafe==2.1.3
  
  #     - matplotlib-inline==0.1.6
  #     - mdurl==0.1.2
  #     - nest-asyncio==1.5.8
  #     - networkx==3.2
  #     - numba==0.59.0
  #     - numpy==1.26.1
  #     - packaging==23.2
  #     - parso==0.8.3
  #     - pexpect==4.8.0
  #     - pickleshare==0.7.5
  #     - pillow==10.0.1
  #     - platformdirs==4.0.0
  #     - prompt-toolkit==3.0.39
  #     - protobuf==4.24.4
  #     - psutil==5.9.6
  #     - ptyprocess==0.7.0
  #     - pure-eval==0.2.2
  #     - pyarrow==13.0.0
  #     - pydeck==0.8.1b0
  #     - pygments==2.16.1
  #     - pyparsing==3.1.1
  #     - python-dateutil==2.8.2
  #     - pytz==2023.3.post1
  #     - pywin32==306
  #     - pyzmq==25.1.1
  #     - referencing==0.30.2
  #     - requests==2.31.0
  #     - retrying==1.3.4
  #     - rich==13.6.0
  #     - rpds-py==0.10.6
  #     - six==1.16.0
  #     - smmap==5.0.1
  #     - stack-data==0.6.3
  #     - streamlit==1.31.1
  #     - tenacity==8.2.3
  #     - tifffile==2023.9.26
  #     - toml==0.10.2
  #     - toolz==0.12.0
  #     - tornado==6.3.3
  #     - traitlets==5.12.0
  #     - typing-extensions==4.8.0
  #     - tzdata==2023.3
  #     - tzlocal==5.2
  #     - urllib3==2.0.7
  #     - validators==0.22.0
  #     - watchdog==3.0.0
  #     - wcwidth==0.2.8
  #     - werkzeug==3.0.1
  #     - widgetsnbextension==4.0.9
  #     - zipp==3.17.0
#prefix: C:\Users\Nomis\anaconda3\envs\microspotreader
